service: bdd-lock-table-${opt:stackName, 'dev'}

provider:
  name: aws
  runtime: python3.7
  region: eu-west-2

functions:
  create-stack:
    handler: src/create_stack.create
    events:
      - http:
          method: POST
          path: create

resources:
    Resources:
      bddLockTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: bddLockTable-${opt:stackName, 'dev'}
          AttributeDefinitions:
            - AttributeName: stackName
              AttributeType: S
            - AttributeName: repoName
              AttributeType: S
            - AttributeName: isAvailable
              AttributeType: S
          KeySchema:
            - AttributeName: stackName
              KeyType: HASH
          GlobalSecondaryIndexes:
            - IndexName: "availableByRepoIndex"
              KeySchema:
                - AttributeName: "repoName"
                  KeyType: "HASH"
                - AttributeName: "isAvailable"
                  KeyType: "RANGE"
              Projection:
                ProjectionType: KEYS_ONLY
          BillingMode: PAY_PER_REQUEST
